[[main]]
title = "Home"
href = "/"
weight = 3

[[main]]
title = "CV"
href = "/assets/pdfs/CV_DZackGarza.pdf"
weight = 5

[[main]]
title = "Papers"
href = "/papers/"
weight = 10

[[main]]
title = "Writing"
weight = 15

  [[main.children]]
  title = "Notes"
  href = "/writing/"
  weight = 10

  [[main.children]]
  title = "Talks"
  href = "/talks/"
  weight = 20

[[main]]
title = "Teaching"
href = "/teaching/"
weight = 25

[[main]]
title = "Blog"
href = "/blog/"
weight = 30

[[main]]
title = "About"
href = "/about/"
weight = 35
